// | Algorithm                        | How It Works                                                                 | Pros                                                        | Cons                                                          | Typical Use / Notes                                |
// | -------------------------------- | ---------------------------------------------------------------------------- | ----------------------------------------------------------- | ------------------------------------------------------------- | -------------------------------------------------- |
// | **FIFO (First-In-First-Out)**    | Remove the page loaded earliest                                              | Simple, easy to implement                                   | Poor performance if old pages still needed (Belady’s anomaly) | Rare, mostly educational                           |
// | **LRU (Least Recently Used)**    | Remove the page least recently accessed                                      | Good approximation of optimal, adaptive to program behavior | Needs tracking usage → hardware/software overhead             | Widely used, good for temporal locality            |
// | **LFU (Least Frequently Used)**  | Remove the page with least number of accesses                                | Keeps frequently used pages                                 | Old, unused pages may remain; slow adaptation                 | Rarely used alone; sometimes combined with aging   |
// | **Optimal (Belady’s Algorithm)** | Remove page not needed for the longest future time                           | Best possible performance                                   | Impossible to implement in real OS (needs future knowledge)   | Used for simulation/research                       |
// | **Clock / Second Chance**        | Circular list; evict pages with reference bit = 0, give second chance if R=1 | Approximates LRU with low overhead, simple                  | Not exact LRU                                                 | Very common in modern OS (Linux, Windows variants) |


